name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      # 1Ô∏è‚É£ R√©cup√©ration du code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2Ô∏è‚É£ Configuration de la cl√© priv√©e SSH
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3Ô∏è‚É£ Ajout de l'h√¥te au known_hosts
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts

      # 4Ô∏è‚É£ D√©ploiement
      - name: Deploy via SSH
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
            cd 	/home/u608034730/domains/immocarrepremium.com/laravel

            echo "üåÄ Mise √† jour du d√©p√¥t..."
            git fetch origin main
            git reset --hard origin/main

            echo "üì¶ Installation des d√©pendances..."
            composer install 
  
            echo "‚öôÔ∏è Optimisation Laravel..."
            php artisan optimize:clear

            npm install

            echo "npm run build"
            
            php artisan optimize
            php artisan migrate 

            echo "‚úÖ D√©ploiement termin√© avec succ√®s !"
          EOF

